name: PR Checks

on:
  pull_request:
    branches: [ master ]

env:
  GH_ACCESS_TOKEN: ${{ secrets.ARMOSEC_GITHUB_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ env.GH_ACCESS_TOKEN }}
        
    - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/armosec/.insteadOf https://github.com/armosec/
    - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/kubescape/.insteadOf https://github.com/kubescape/
    
    - name: Set up Go

      uses: actions/setup-go@v4
      with:
        go-version: "1.20"

    - name: Get dependencies
      run: go mod download
      
    - name: Test
      run: go test ./... -v --race  -covermode=count -coverprofile=coverage.out
 
    - name: Convert coverage count to lcov format
      uses: jandelgado/gcov2lcov-action@v1
      
    - name: Submit coverage tests to Coveralls
      continue-on-error: true
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
