name: Release-Tag
on:
  push:
    branches: [ master, "*" ] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
      
    - name: Test & coverage
      id: unit-test
      run: go test -v ./... -covermode=count -coverprofile=coverage.out

    - name: Convert coverage count to lcov format
      uses: jandelgado/gcov2lcov-action@v1
      
    - name: Submit coverage tests to Coveralls
      continue-on-error: true
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov

    - name: Create a release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.0.${{ github.run_number }}
        release_name: Release v0.0.${{ github.run_number }}
        draft: false
        prerelease: false
